### PR TITLE
Improve error handling and reporting.

### PR DESCRIPTION
**Pull request by briansmith**

### CODE REVIEW

**Comment by briansmith** [comment]
On my system the program fails because it triggers this code path in BN_mod_exp_recp:

```c
    if (BN_get_flags(p, BN_FLG_CONSTTIME) != 0
            || BN_get_flags(a, BN_FLG_CONSTTIME) != 0
            || BN_get_flags(m, BN_FLG_CONSTTIME) != 0) {
        /* BN_FLG_CONSTTIME only supported by BN_mod_exp_mont() */
        BNerr(BN_F_BN_MOD_EXP_RECP, ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED);
        return 0;
    }
```

**Comment by briansmith** [comment]
I suspect you see BN_mod_exp fail on macOS but you don't see if fail on Ubuntu maybe because the "should not be called" check might not be in Ubuntu's copy. Not sure. Regardless, IIUC the reason you see a difference in results is because you are ignoring the error return values from the OpenSSL functions. In this PR I fixed a couple of cases but there are many more cases where you need to check for errors and bail early.

**Comment by briansmith** [comment]
> On my system the program fails because it triggers this code path in BN_mod_exp_recp:
> ```
>     if (BN_get_flags(p, BN_FLG_CONSTTIME) != 0
>             || BN_get_flags(a, BN_FLG_CONSTTIME) != 0
>             || BN_get_flags(m, BN_FLG_CONSTTIME) != 0) {
>         /* BN_FLG_CONSTTIME only supported by BN_mod_exp_mont() */
>         BNerr(BN_F_BN_MOD_EXP_RECP, ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED);
>         return 0;
>     }
> ```

When I remove this code from OpenSSL (the latest commit on the 1.0.2 branch) and build it, I get no output from the program on Ubuntu, which I believe means it succeeded.

**Comment by rbost** [comment]
Thanks!

What I still do not understand is:
1. why does the BN_mod_exp_recp routine does not fail every time?
2. why, when the numbers output by the code are later hardcoded check_fixed_string, the error does not show up again?

**Comment by briansmith** [comment]
> why does the BN_mod_exp_recp routine does not fail every time?

When you generate an RSA key, the secret values `d`, `p`, `q`, `dP`, `dQ`, etc. have `BN_FLG_CONSTTIME` set on them. `BN_mod_exp_recp` fails when any of its inputs have `BN_FLG_CONSTTIME` set.

> why, when the numbers output by the code are later hardcoded check_fixed_string, the error does not show up again?

They don't have `BN_FLG_CONSTTIME` set.

**Comment by rbost** [comment]
That I got. What I don't understand is why, when d is generated from the RSA generation function, 
`BN_FLG_CONSTTIME` is sometimes set, and sometimes not. And yes, when it is set, the test fails 
(cf. c2a1ef6ce9828f456cd72a6414064f842bb6911d)

**Comment by briansmith** [comment]
> What I don't understand is why, when d is generated from the RSA generation function,
> BN_FLG_CONSTTIME is sometimes set, and sometimes not.

Any case where `d` doesn't have `BN_FLG_CONSTTIME` is a bug.

**Pull request merged**
